base:
  project: RLNav

neptune:
  monitoring_times: False

scenarios:
  path: data/scenarios/
  n_scenarios: 1
  priority: [
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003,
  ]
  skip_first: 0
  n_generations: 10
  subscenarios: [
    # scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_00_DEBUG,
    # scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_01_LOWH_LOWV, # No reference data
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_03_LOWH_LOWV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_05_LOWH_LOWV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_07_LOWH_LOWV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_11_LOWH_LOWV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_04_MIDH_MIDV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_08_MIDH_MIDV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_10_MIDH_MIDV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_02_MIDH_HIGHV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_06_MIDH_HIGHV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_09_MIDH_HIGHV,
  ]

processed_data:
  path: data/RLNav/processed/

transformed_data:
  path: data/RLNav/transformed/

training:
  num_parallel_environments: 20
  active_environments_per_iteration: 10
  rnn:
    enable: True
    window_size: 1