base:
  project: RLNav

neptune:
  monitoring_times: False
  tensorboard: False

scenarios:
  path: data/scenarios/
  n_scenarios: -1
  priority: [
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003,
  ]
  skip_first: 10
  n_generations: 1
  subscenarios: [
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_01_LOWH_LOWV,
    scenario_910_000_CS_KINEMATIC_20230221_HIGHWAY_01_LOWH_LOWV,
    scenario_911_000_CS_KINEMATIC_20230227_SEMIURBAN_01_LOWH_LOWV,
    scenario_912_000_CS_KINEMATIC_20230327_HIGHWAY_01_LOWH_LOWV,
    scenario_914_000_CS_KINEMATIC_20230518_HIGHWAY_01_LOWH_LOWV,
    scenario_915_000_CS_KINEMATIC_20230522_SEMIURBAN_1_01_LOWH_LOWV,
    scenario_917_000_CS_KINEMATIC_20230525_URBAN_01_LOWH_LOWV,
    scenario_918_000_CS_KINEMATIC_20230529_HIGHWAY_01_LOWH_LOWV,
    scenario_916_000_CS_KINEMATIC_20230522_SEMIURBAN_2_02_LOWH_LOWV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_03_LOWH_LOWV,
    scenario_911_000_CS_KINEMATIC_20230227_SEMIURBAN_03_LOWH_LOWV,
    scenario_917_000_CS_KINEMATIC_20230525_URBAN_03_LOWH_LOWV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_04_LOWH_LOWV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_05_LOWH_LOWV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_07_LOWH_LOWV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_11_LOWH_LOWV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_02_LOWH_MIDV,
    scenario_911_000_CS_KINEMATIC_20230227_SEMIURBAN_02_LOWH_MIDV,
    scenario_917_000_CS_KINEMATIC_20230525_URBAN_02_LOWH_MIDV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_05_LOWH_MIDV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_03_MIDH_LOWV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_07_MIDH_LOWV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_10_MIDH_LOWV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_06_MIDH_MIDV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_06_MIDH_MIDV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_12_MIDH_MIDV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_14_MIDH_MIDV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_16_MIDH_MIDV,
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_04_MIDH_HIGHV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_08_MIDH_HIGHV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_15_MIDH_HIGHV,
    scenario_911_000_CS_KINEMATIC_20230227_SEMIURBAN_04_HIGHH_LOWV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_02_HIGHH_MIDV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_01_HIGHH_HIGHV,
    scenario_916_000_CS_KINEMATIC_20230522_SEMIURBAN_2_01_HIGHH_HIGHV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_09_HIGHH_HIGHV,
    scenario_913_000_CS_KINEMATIC_20230310_URBAN_13_HIGHH_HIGHV,
  ]
  subscenarios_done: 0
  curriculum_learning: True

processed_data:
  path: data/RLNav/processed/

transformed_data:
  path: data/RLNav/transformed/

training:
  num_parallel_environments: 20
  active_environments_per_iteration: 10
  rnn:
    enable: True
    window_size: 1

eval:
  model_path: models/
  model_name: policy_247_enc