base:
  project: RLNav

neptune:
  monitoring_times: True

scenarios:
  path: data/scenarios/
  n_scenarios: 1
  priority: [
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003,
  ]
  skip_first: 0
  n_generations: 1
  subscenarios: [
    scenario_931_000_GPSGALBDS_CSIRELAND_L1L2_KINEMATIC_20231003_URBAN_1,
  ]

processed_data:
  path: data/RLNav/processed/

transformed_data:
  path: data/RLNav/transformed/

rnn:
  enable: True
  window_size: 1