class E_CONSTELLATION:
    E_CONSTEL_NONE = 0
    E_CONSTEL_GPS = 1
    E_CONSTEL_GAL = 2
    E_CONSTEL_BDS = 3


# CONSTANTS DEFINITIONS (DEFINES & CONSTS)
NUM_CHANNELS = 2

NUM_CONSTELS = 3  # GPS, GAL, BDS
MAX_SATS_GPS = 40
MAX_SATS_GAL = 40
MAX_SATS_BDS = 63
MAX_SATS = MAX_SATS_GPS + MAX_SATS_GAL + MAX_SATS_BDS  # GPS + GAL + BDS

SECURITY = True
